### ISSUE TITLE
Change Host Country in all templates

### ISSUE THREAD

**Issue by noahalorwu** [djangocon/2023.djangocon.africa#29]

**Comment by kafui4k** [comment]
Do we already have the Host Country name approved?

**Comment by noahalorwu** [comment]
Well, we are yet to conclude but definitely it'll be hosted at Tanzania

**Comment by kafui4k** [comment]
Noted

**Comment by ephraimduncan** [comment]
Do we have a specific city?

**Comment by noahalorwu** [comment]
Not yet, would update the issue with it when agreed upon

**Comment by datgerhardt** [comment]
Okay
