### ISSUE TITLE
Navbar Length

### ISSUE THREAD

**Issue by ephraimduncan** [djangocon/2023.djangocon.africa#30]
The navigation here is different from the design. The width is more wider compared to the design

### Site
![Screenshot 2022-12-30 at 15 17 38](https://user-images.githubusercontent.com/55143799/210085781-254d05ba-26e5-43d7-97e8-9bba2acbc515.png)

### Design
![Screenshot 2022-12-31 at 02 38 27](https://user-images.githubusercontent.com/55143799/210122602-3586cf1a-4d47-4d07-a6ac-55326af6b797.png)

**Comment by mihrab34** [comment]
@noahalorwu
