### ISSUE TITLE
Mobile Navigation View

### ISSUE THREAD

**Issue by noahalorwu** [djangocon/2023.djangocon.africa#32]

**Comment by ephraimduncan** [comment]
@noahalorwu 

<img width="348" alt="Screenshot 2023-01-30 at 20 48 16" src="https://user-images.githubusercontent.com/55143799/215591841-0b2935c0-20c7-4aaa-9d63-5bf9d3cfd546.png">

What do you think of this. I move the logo and hamburger on the same line and move the date below them and hide the get ticket inside the hamburger?

**Comment by noahalorwu** [comment]
Yes, do go with that flow
