### ISSUE TITLE
Visa Supports Page

### ISSUE THREAD

**Issue by noahalorwu** [djangocon/2023.djangocon.africa#7]

**Comment by seun-beta** [comment]
Hello @noahalorwu 

I hope you are good. 

I've gone through the design but I cannot seem to find where the visa sponsorship page fits in the UI.

**Comment by noahalorwu** [comment]
The visa page has been implemented. Do let me know your availability so that I can walk you through the codebase and what's there to pick up @seun-beta

**Comment by seun-beta** [comment]
Hello @noahalorwu 

I would be available tomorrow for the walkthrough. I would be available from 8am to 7pm WAT. 

Please let me know what time works for you.
