### ISSUE TITLE
Invitation Letter Page

### ISSUE THREAD

**Issue by noahalorwu** [djangocon/2023.djangocon.africa#8]

**Comment by Globak143** [comment]
Hi Noah,

Is there a guideline for the invitation letter content or will I have to develop it? Thanks

**Comment by noahalorwu** [comment]
There's an already content for the invitation letter. We need to connect it to hook it to an api. I can guide you through. Lemme know your availability

**Comment by Globak143** [comment]
> There's an already content for the invitation letter. We need to connect it to hook it to an api. I can guide you through. Lemme know your availability

ok. Great!
